import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { UserAuthContextProvider } from '@/context/UserContext';

import './globals.css'
import { StoreContextProvider } from '@/context/StoreContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserAuthContextProvider>
          <StoreContextProvider>
            {children}
          </StoreContextProvider>
        </UserAuthContextProvider>
      </body>
    </html>
  )
}
